<!DOCTYPE html>
<html class="screen-desktop-wide device-desktop"><head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>用户管理</title>
    <meta name="description" content="">
    <![endif]--></head>
<body>
<div class="doc doc-login">
    <div class="login-form">
        <div class="form">
            <div class="adminlogo"><h1>请登录</h1></div>
            <form id="loginForm" action="/admin/index/login" method="post">
                <div class="formitem">
                    <input type="text" class="form-ipt" id="loginform_user" name="adminName" placeholder="请输入登录账号">
                    <?php if (isset($accountMsg) && !empty($accountMsg)): ?><div class="errormsg"><i class="icon icon-warning-sign"></i> <?php echo $accountMsg; ?></div><?php endif;?>
                </div>
                <div class="formitem">
                    <input type="password" class="form-ipt" id="loginform_pass" name="adminPwd" placeholder="请输入登录密码">
                    <?php if (isset($passwordMsg) && !empty($passwordMsg)): ?><div class="errormsg"><i class="icon icon-warning-sign"></i> <?php echo $passwordMsg; ?></div><?php endif;?>
                </div>

                <div class="action">
                    <button class="subbtn" type="submit">登录 </button>
                </div>
            </form>
        </div>
    </div>
</div>

