<?php
/**
 * 公用controller，除了index其他页面不需要登录，切记此controller中的action为非必须登录action
 */
namespace MyApp\Controllers\Admin;

use MyApp\Controllers\Admin\BaseController;
use MyApp\Models\Group;
use MyApp\Models\User;

class IndexController extends BaseController
{

    public function initialize()
    {
        echo parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        //        $info                  = new Info;
        //        $where["AND"]["id[>]"] = 6;
        //        $data                  = $info->select("*", $where);
        //        var_dump($data);
        //        $this->view->setVar('company', 111);
    }
    public function loginAction()
    {
        if ($this->request->isPost()) {
            $adminName = $this->request->getPost('adminName', 'string');
            $adminPwd  = $this->request->getPost('adminPwd', 'string');

            if (empty($adminName)) {
                $this->view->accountMsg = '请输入用户名！';
            } elseif (empty($adminPwd)) {
                $this->view->passwordMsg = '请填写登录密码！';
            } else {
                ////这里执行数据库验证
                $user = new User();

                $check = $user->checkUser($adminName, $adminPwd);
                if ($check === null) {
                    $this->view->accountMsg = '用户不存在！';
                } elseif (isset($check['isAdmin']) && !$check['isAdmin'] == true) {
                    $this->view->accountMsg = '密码错误，请重新输入！';
                } else {
                    // var_dump($check['info']);
                    //echo 6555;die;

                    ///获取权限
                    $super = parent::isSuper($check['info']['groupId']);
                    // var_dump($super);
                    //die;
                    $add = parent::hasAdd($check['info']['groupId']);
                    //var_dump($super);die;
                    //注册seeion 存储用户名 权限
                    $this->session->set("adminName", $check['info']['name']);
                    $this->session->set("groupId", $check['info']['groupId']);
                    $this->session->set("super", $super);

                    //var_dump($this->session->get("adminName"));die;

                    $users = (new User())->getUser();
                    $this->view->setVar('users', $users);
                    $this->view->pick('index/list');
                    //$this->view->redirect('admin/index/list');
                    //$this->listAction();

                }
            }
        }
    }

    public function listAction()
    {
        $users = (new User())->getUser();
        $this->view->setVar('users', $users);
    }
    public function addAction()
    {
        $group = (new Group())->getGroups();
        // var_dump($group);die;
        $this->view->setVar('group', $group);

    }
    public function saveAction()
    {
        $request = $this->request;
        $name    = $request->getPost('name');
        $pwd     = $request->getPost('pwd');
        $sex     = $request->getPost('sex');
        $mobile  = $request->getPost('mobile');
        $group   = $request->getPost('group');
        $user    = new User();
        $this->db->insert('user',
            ['name'   => $name,
                'pwd'     => $pwd,
                'sex'     => $sex,
                'phone'   => $mobile,
                'groupId' => $group,
            ]);
        $users = (new User())->getUser();
        $this->view->setVar('users', $users);
        $this->view->pick('index/list');
    }

}
